title: Lord of the Strings
description: A guitar robot that can strum and palm mute
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
baseurl: "/ece3140-sp2025/ahl92-am2736-nsv23"
plugins:
- jekyll-remote-theme # add this line to you plugin list if you are using a different setup
nav:
  - title: Overview
    url: {{site.baseurl}}/
  - title: Technical Approach
    url: {{site.baseurl}}/technical
  - title: Testing/Debugging Approach
    url: {{site.baseurl}}/testing
  - title: Teamwork
    url: {{site.baseurl}}/team
  - title: Media/Demo
    url: {{site.baseurl}}/media
  - title: Future Improvements
    url: {{site.baseurl}}/improv
  - title: Outside Resources
    url: {{site.baseurl}}/resources